logging:
  file_path: "/communityZ"

dayz:
  root: "DayZServerBackup20220728/"
  log_dir: 'communityZ/'
  ban:
    file_path: "ban.txt"
    file_csv_path: "ban.csv"
    back_file_path: "ban_backup.txt"
  settings:
    file_path: "dayzsettings.xml"
    back_file_path: "dayzsettings_backup.xml"

discord:
  guild: "1164838927807561759"
  channel_id:
    bot_log: 1216711729723998248 #"786607495413891113"
    

autoMod:
  maxWeaponDistance:
    maximumWarnings: 3
    MaxWarningTimeSpan: 5 #in seconds
    weapons:
      #Pistols:
      IJ-70:
        warn: 2
        ban: 80
      Mlock-91:
        warn: 50
        ban: 80
      Revolver:
        warn: 50
        ban: 80
      Derringer:
        warn: 30
        ban: 50
      #Shotguns:
      BK-133:
        warn: 20
        ban: 50
      #Submachineguns:
      #automaticRifles:
      DMR:
        warn: 100
        ban: 200
      #Snipers:
      CR-527:
        warn: 300
        ban: 800

