logging:
  file_path: "/communityZ"

dayz:
  root: 'DayZServerBackup20220728/'
  log_dir: 'communityZNew/'
  serverDZ: 'serverDZ.cfg'
  ban:
    file_path: "ban.txt"
    file_csv_path: "ban.csv"
    back_file_path: "ban_backup.txt"
  settings:
    file_path: "dayzsettings.xml"
    back_file_path: "dayzsettings_backup.xml"

discord:
  guild: "1164838927807561759"
  channel_id:
    bot_log: 1216711729723998248 #"786607495413891113"
    

autoMod:
  combatlogTimeMinutes: 15
  maxWeaponDistance:
    maxWarningAmount: 3
    maxWarningTimeSpan: 5 #in seconds
    weapons:
      #Pistols:
      IJ-70:
        interval: 50
        ban: 80
      Mlock-91:
        interval: 50
        ban: 80
      Revolver:
        interval: 50
        ban: 80
      Derringer:
        interval: 50
        ban: 80
      FX-45:
        interval: 50
        ban: 80
      #Shotguns:
      BK-133:
        interval: 30
        ban: 50
      #Submachineguns:
      #automaticRifles:
      DMR:
        interval: 100
        ban: 400
      #Snipers:
      CR-527:
        interval: 100
        ban: 10000
        maximumWarnings: 2
        MaxWarningTimeSpan: 3 #in seconds
      Blaze:
        interval: 100
        ban: 10000
        maximumWarnings: 3
        MaxWarningTimeSpan: 5 #in seconds


